### PR TITLE
Workaround bug in macOS 14.4.1 and later where encoding HEIC fails

### LINKED ISSUE #66: writeImageAtIndex:962: *** CMPhotoCompressionSessionAddImage: err = kCMPhotoError_UnsupportedOperation [-16994]    (codec: 'hvc1')
### An _issue_ or a _feature request_
`writeImageAtIndex:962: *** CMPhotoCompressionSessionAddImage: err = kCMPhotoError_UnsupportedOperation [-16994]    (codec: 'hvc1')`

### Device and System
- MacBook Pro, 15-inch, 2019
- macOS 14.4.1 (23E224)

### Appearance
`l11n: Localization.Wallpaper.Create.failureDescription`

image

Commit ID: `e831db45a4848b61a156745b1fc8e1492e7510cc`

image

Assets(images from https://github.com/rlxone/Equinox/tree/main/repo)
- [screen.png](https://github.com/rlxone/Equinox/blob/main/repo/screen.png)
- [screen1.jpg](https://github.com/rlxone/Equinox/blob/main/repo/screen1.jpg)

### -
Changing the pixel format from `yuvj420p` to `yuvj444p` of  [screen1.jpg](https://github.com/rlxone/Equinox/blob/main/repo/screen1.jpg) with `ffmpeg -hide_banner -i screen1.jpeg -pix_fmt yuvj444p screen1.yuvj444p.jpg`, or changing format from `jpg` to `png` , then everything works okay.

image

### PR DESCRIPTION
**Pull request by kyleerhabor**
Closes #66 and #68.

### CODE REVIEW

**Comment by kyleerhabor** [comment]
CC: @rlxone

**Review by CasualDeveloper — APPROVED** [review]

**Comment by rlxone** [comment]
Hi, thanks for the fix, do we know what versions were affected? Is it still an issue?

**Comment by rlxone** [comment]
Can't reproduce on my M1 Mac Mini (macOS 14.6.1 (23G93)) using images from #66. 
Do you use macs with intel processors?
image

**Comment by rlxone** [comment]
Hey @dreampiggy, sorry for bothering you, but seems like you investigated this issue a lot. What is the current state of the issue? Have we reported this bug to Apple?

**Comment by dreampiggy** [comment]
No. I didn't fired radar for this.

The HEVC encoding seems fails on macOS 15.0 beta, which is not the same issue.

If you found this bug in macOS 14.4.1 and has workaround (using compression quality), maybe it's another case

**Comment by dreampiggy** [comment]
Actually, if Apple's framework is not trustable, you can provide a fallback workaround

Since HEVC/HEIF is standard, there are also open-source encode/decode lib, like https://github.com/strukturag/libheif

If you don't like the C API, just use my wrapper API for encoding https://github.com/SDWebImage/SDWebImageHEIFCoder

**Comment by kyleerhabor** [comment]
Hello,

@CasualDeveloper [here is a build with the relevant changes included](https://dropover.cloud/8d1155).

@rlxone this continues to be a relevant issue. If you're not experiencing this on your M1 Mac Mini, then the issue may be Intel-specific, as my 2019 MacBook Pro running macOS Sonoma 14.6.1 (23G93) exhibits the bug. Unfortunately, I'm not aware of the exact affected version range except for 14.4.1 being a start.

**Comment by zgosalvez** [comment]
I tried @CasualDeveloper's build, and I can confirm that this is still an issue on my Intel-based Mac. 🙅🏼 

> Hello,
> 
> @CasualDeveloper [here is a build with the relevant changes included](https://dropover.cloud/8d1155).
> 
> @rlxone this continues to be a relevant issue. If you're not experiencing this on your M1 Mac Mini, then the issue may be Intel-specific, as my 2019 MacBook Pro running macOS Sonoma 14.6.1 (23G93) exhibits the bug. Unfortunately, I'm not aware of the exact affected version range except for 14.4.1 being a start.

**Comment by zgosalvez** [comment]
I tried @CasualDeveloper build and I can confirm that it works successfully on my Intel-based Mac. ✅ 

> Hello,
> 
> @CasualDeveloper [here is a build with the relevant changes included](https://dropover.cloud/8d1155).
> 
> @rlxone this continues to be a relevant issue. If you're not experiencing this on your M1 Mac Mini, then the issue may be Intel-specific, as my 2019 MacBook Pro running macOS Sonoma 14.6.1 (23G93) exhibits the bug. Unfortunately, I'm not aware of the exact affected version range except for 14.4.1 being a start.

**Comment by CasualDeveloper** [comment]
@rlxone @kyleerhabor

I can confirm that that Kyle's build works on my MacBook Pro (2019, Intel i9) running latest macOS Sonoma

**Comment by CasualDeveloper** [comment]
FYI I've filed a radar in Feedback Assistant on this issue, and also a copy of it on [OpenRadar](https://openradar.appspot.com/15008483).

**Comment by CasualDeveloper** [comment]
Hey y'all, good news! 😊

The bug doesn't seem to occur on my MacBook Pro (2019, Intel i9) running macOS Sequoia 15.0 Beta (24A5331b) – tested with Equinox v3.0 from App Store.

Creating an Appearance-type wallpaper with two images now complete successfully (I'm assuming with 1.0 quality, since the files sizes seem bigger compared to using 0.9999999 quality)

**Comment by kyleerhabor** [comment]
That's great. I wouldn't mind amending this pull request with checks for the earliest resolved version (either Sequoia 15 or a later version of Sonoma) and an Intel device.

**Comment by rlxone** [comment]
Thank you all for helping with this!
@kyleerhabor feel free to go ahead, i can merge it as soon as you ready with the new additions.

**Comment by kyleerhabor** [comment]
@rlxone I've added the additions.

**Comment by rlxone** [comment]
@kyleerhabor sweet, i'll review tomorrow

**Review by rlxone — APPROVED** [review]

**Comment by rlxone** [comment]
@kyleerhabor looks good to me, i'll release a new app store build in a couple of days.
Thanks everyone for helping with his again!

**Pull request merged**
